export default {
  products: [
    {
      id: "0",
      name: "Slim Shirt",
      category: "Shirt",
      image: "/image/d1.jpg",
      brand: "Zoli",
      price: 57,
      rating: 4.7,
      numReviews: 23,
      inStock: 6,
    },
    {
      id: "1",
      name: "Slim Shirt",
      category: "Shirt",
      image: "/image/d1.jpg",
      brand: "Zari",
      price: 57,
      rating: 4.5,
      numReviews: 230,
      inStock: 7,
    },
    {
      id: "2",
      name: "Slim Shirt",
      category: "Skirt",
      image: "/image/d1.jpg",
      brand: "Kaoli",
      price: 97,
      rating: 4.8,
      numReviews: 2,
      inStock: 8,
    },
    {
      id: "3",
      name: "Slim Shirt",
      category: "Jacket",
      image: "/image/d1.jpg",
      brand: "Zoli",
      price: 57,
      rating: 4.7,
      numReviews: 23,
      inStock: 6,
    },
    {
      id: "4",
      name: "Slim Shirt",
      category: "Shirt",
      image: "/image/d1.jpg",
      brand: "Derat",
      price: 39,
      rating: 4.1,
      numReviews: 34,
      inStock: 5,
    },
    {
      id: "5",
      name: "Dark Shirt",
      category: "Jacket",
      image: "/image/d1.jfif",
      brand: "Fonai",
      price: 89,
      rating: 4.5,
      numReviews: 93,
      inStock: 0,
    },
  ],
};
